### ISSUE TITLE
Relax `arrow-parens`

### ISSUE THREAD

**Issue by ngryman** [zapier/eslint-plugin-zapier#23]
Hey, very small thing but I'd like to make a proposition here.
I do agree that it's better for readability and standardization, no question about that.

However, when arrow functions are used as callbacks removing those parens can actually help in code readability:

```js
people.filter((p) => p.isOnline) // vs.
people.filter(p => p.isOnline)
````

I would propose to keep this rule for function declarations using the arrow syntax, but relax it for anonymous functions.

```js
// good
const onChange = (e) => {}
people.filter(p => p.isOnline)

// bad
const onChange = e => {}
people.filter((p) => p.isOnline)
```

What do you think?

@vitorbal I don't think `eslint` offers a way to do so does it?

**Comment by vitorbal** [comment]
@ngryman Thanks for the suggestion!

I don't think ESLint supports allowing no-parens only for callbacks.

However, it doesn't really matter, since prettier takes over all formatting / code style rules anyway. If you take a look at some code in the `zapier/zapier` folder, you'll see that all arrow functions with only 1 parameter get formatted without parens.

I realize some of the stylistic rules configured in `eslint-plugin-zapier` that only apply to the non-prettier config (`plugin:zapier/base`) can cause some confusion, since we disable all of them for the prettier config (`plugin:zapier/prettier`) via [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).

I think we should actually deprecate `zapier/base` and only expose the `zapier/prettier` config, and then get rid of all stylistic rules from `eslint-plugin-zapier`.
Initially, I thought it would be unfair to force all projects to use `prettier`, but it has worked quite well so far for `zapier/zapier` so I think it's fair to do it to avoid us having to maintain two different sets of configs.

**Comment by ngryman** [comment]
Alright thanks for the clarifications!
